// USER STARTS
export const GET_USER = 'GET_USER'
export const RESET_AUTH = 'RESET_AUTH'
export const USER_LOGIN = 'USER_LOGIN'
export const REGISTER_USER = 'REGISTER_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOADING = 'LOADING'
export const GET_ERROR = 'GET_ERROR'
export const CLEAR_ERROR = 'GET_ERROR'
export const AUTH_ERROR = 'AUTH_ERROR'
export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME'
export const SEND_FORGOT_PASSWORD_EMAIL = 'SEND_FORGOT_PASSWORD_EMAIL'
export const SEND_FORGOT_PASSWORD_EMAIL_ERROR = 'SEND_FORGOT_PASSWORD_EMAIL_ERROR'
export const CONFIRMATION_CODE_ERROR = 'CONFIRMATION_CODE_ERROR'
export const CANCEL_FORGOT_PASSWORD = 'CANCEL_FORGOT_PASSWORD'
export const CONFIRMATION_CODE_SUCCESS = 'CONFIRMATION_CODE_SUCCESS'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const USER_ADD_PROFILE_PHOTO = 'USER_ADD_PROFILE_PHOTO'
export const REMOVE_PROFILE_PHOTO = 'REMOVE_PROFILE_PHOTO'
export const GET_USER_REVIEWS = 'GET_USER_REVIEWS'
export const USER_DELETE_REVIEW = 'USER_DELETE_REVIEW'
// USER ENDS

// SELLER STARTS
export const SELLER_REGISTER = 'SELLER_REGISTER'
export const SELLER_LOADING = 'SELLER_LOADING'
export const SELLER_LOGIN = 'SELLER_LOGIN'
export const SELLER_ERROR = 'SELLER_ERROR'
export const SELLER_LOGOUT = 'SELLER_LOGOUT'
export const GET_CURRENT_SELLER = 'GET_CURRENT_SELLER'
export const SELLER_SEND_FORGOT_PASSWORD_EMAIL = 'SELLER_SEND_FORGOT_PASSWORD_EMAIL'
export const SELLER_CHECK_PASSWORD_TOKEN = 'SELLER_CHECK_PASSWORD_TOKEN'
export const SELLER_CHANGE_PASSWORD = 'SELLER_CHANGE_PASSWORD'
export const SELLER_RESET_PASSWORD_TOKEN_ERROR = 'SELLER_RESET_PASSWORD_TOKEN_ERROR'
export const SELLER_RESET_PASSWORD_ERROR = 'SELLER_RESET_PASSWORD_ERROR'
export const SELLER_ROUTE = 'SELLER_ROUTE'
export const NOT_SELLER_ROUTE = 'NOT_SELLER_ROUTE'
export const UPDATE_SELLER = 'UPDATE_SELLER'
export const GET_ALL_SELLER_PRODUCTS = 'GET_ALL_SELLER_PRODUCTS'
export const SELLER_DELETE_PRODUCT = 'SELLER_DELETE_PRODUCT'
export const SELLER_UPDATE_PRODUCT = 'SELLER_UPDATE_PRODUCT'
export const GET_SELLER_CHARTS = 'GET_SELLER_CHARTS'
// SELLER ENDS

// PRODUCT STARTS
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
// PRODUCT ENDS

// SELLER ORDER STARTS
export const GET_SELLER_ORDERS = 'GET_SELLER_ORDERS'
export const DENY_ORDER_CANCEL_REQUEST = 'DENY_ORDER_CANCEL_REQUEST'
export const CANCEL_ORDER = 'CANCEL_ORDER'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
// SELLER ORDER ENDS

// CART STARTS
export const ADD_CART = 'ADD_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const REMOVE_ALL_CART_ITEM = 'REMOVE_ALL_CART_ITEM'
export const GET_CART = 'GET_CART'
export const INCREASE_CART_ITEM = 'INCREASE_CART_ITEM'
export const DECREASE_CART_ITEM = 'DECREASE_CART_ITEM'
export const CART_ERROR = 'CART_ERROR'
export const SELECT_CART_ITEM = 'SELECT_CART_ITEM'
export const DONT_SELECT_CART_ITEM = 'DONT_SELECT_CART_ITEM'
// CART ENDS

// WISHLIST STARTS
export const ADD_WISHLIST = 'ADD_WISHLIST'
export const REMOVE_WISHLIST = 'REMOVE_WISHLIST'
export const REMOVE_ALL_WISHLIST = 'REMOVE_ALL_WISHLIST'
export const GET_WISHLIST = 'GET_WISHLIST'
export const WISHLIST_ERROR = 'WISHLIST_ERROR'
// WISHLIST ENDS

// PRODUCT REVIEW STARTS
export const ADD_REVIEW = 'ADD_REVIEW'
export const UPDATE_REVIEW = 'UPDATE_REVIEW'
export const GET_REVIEWS = 'GET_REVIEWS'
export const DELETE_REVIEW = 'DELETE_REVIEW'
export const PRODUCT_REVIEW_ERROR = 'PRODUCT_REVIEW_ERROR'
// PRODUCT REVIEW ENDS

// SELLER RATINGS STARTS
export const GET_RATED_SELLERS_FOR_SELLER = 'GET_RATED_SELLERS_FOR_SELLER'
export const GET_RATED_SELLERS_FOR_USER = 'GET_RATED_SELLERS_FOR_USER'
export const DELETE_SELLER_RATING = 'DELETE_SELLER_RATING'
export const RATE_SELLER = 'RATE_SELLER'
export const RATE_SELLER_LOADING = 'RATE_SELLER_LOADING'
export const RATE_SELLER_ERROR = 'RATE_SELLER_ERROR'
// SELLER RATINGS ENDS

// SEARCH STARTS
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY'
export const SEARCH_PRODUCT_LOADING = 'SEARCH_PRODUCT_LOADING'
// SEARCH STARTS

// ORDER STARTS
export const CREATE_ORDER = 'CREATE_ORDER'
export const GET_ORDERS = 'GET_ORDERS'
export const ORDER_ERROR = 'ORDER_ERROR'
export const ORDER_LOADING = 'ORDER_LOADING'
export const ORDER_CANCEL_REQUEST = 'ORDER_CANCEL_REQUEST'
// ORDER ENDS

// ADDRESS STARTS
export const CREATE_ADDRESS = 'CREATE_ADDRESS'
export const GET_ADDRESSES = 'GET_ADDRESSES'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const DELETE_ADDRESS = 'DELETE_ADDRESS'
export const ADDRESS_ERROR = 'ADDRESS_ERROR'
export const ADDRESS_LOADING = 'ADDRESS_LOADING'
export const SELECT_ADDRESS = 'SELECT_ADDRESS'
export const CREATE_BILLING_ADDRESS = 'CREATE_BILLING_ADDRESS'
export const SELECT_BILLING_ADDRESS = 'SELECT_BILLING_ADDRESS'
export const DELETE_BILLING_ADDRESS = 'DELETE_BILLING_ADDRESS'
export const UPDATE_BILLING_ADDRESS = 'UPDATE_BILLING_ADDRESS'
// ADDRESS ENDS

// CHAT STARTS
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const CREATE_CHATROOM = 'CREATE_CHATROOM'
export const GET_CHATROOMS = 'GET_CHATROOMS'
export const SET_ACTIVE_CHATROOM = 'SET_ACTIVE_CHATROOM'
export const CHAT_ERROR = 'CHAT_ERROR'
export const FORBIDDEN_ROOM = 'FORBIDDEN_ROOM'
export const GET_CHATROOM_MESSAGES = 'GET_CHATROOM_MESSAGES'
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
// CHAT STARTs
